model_name: NousResearch/DeepHermes-3-Mistral-24B-Preview
steering_vector_dir: /workspace/SteerKep/steer-data/vectors
steering_datasets_dir: /workspace/SteerKep/steer-data/datasets
steering_vector_name: junk-healthy-24b
behavior_layer_ids: [29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
behavior_vector_strength: 2
max_new_tokens: 256
use_local: true
cache_dir: /workspace/.cache/huggingface